# Generated by Django 2.2.14 on 2020-07-10 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_test"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tejghgh",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("jhgfhjgjh", models.BigIntegerField()),
            ],
        ),
    ]
