# Generated by Django 2.2.14 on 2020-07-10 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_tejghgh'),
    ]

    operations = [
        migrations.CreateModel(
            name='HJGFFJHGJG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nhgvjhgjhgjg', models.BigIntegerField()),
            ],
        ),
    ]
